openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger World
  license:
    name: MIT
servers:
  - url: http://localhost:9092/
paths:
  /greeting/greet:
    get:
      tags:
        - greeting
      operationId: getGreeting
      summary: Get a greeting message
      parameters:
        - name: name
          required: false
          in: query
          description: The name used in the greeting response
          schema:
            type: string
      responses:
        '200':
          description: A success response with a greeting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /countries:
    get:
      summary: List all countries
      operationId: listCountries
      tags:
        - countries
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of countries
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Countries"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cities:
    get:
      summary: List all cities
      operationId: listCities
      tags:
        - cities
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of cities
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cities"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Greeting:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    City:
      type: object
      x-class-extra-annotation: "@jakarta.persistence.Entity"
      required:
        - id
        - name
        - countrycode
        - district
        - population
      properties:
        id:
          type: integer
          format: int64
          x-field-extra-annotation: "@jakarta.persistence.Id"
        name:
          type: string
        countrycode:
          type: string
        district:
          type: string
        population:
          type: integer
          format: int64
    Cities:
      type: array
      items:
        $ref: "#/components/schemas/City"
    Country:
      type: object
      x-class-extra-annotation: "@jakarta.persistence.Entity"
      required:
        - code
        - name
        - continent
        - region
        - capital
      properties:
        code:
          type: string
          x-field-extra-annotation: "@jakarta.persistence.Id"
        name:
          type: string
        continent:
          type: string
        region:
          type: string
        capital:
          type: integer
          format: int64
    Countries:
      type: array
      items:
        $ref: "#/components/schemas/Country"
    Error:
      type: object
      required:
        - code
        - name
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string